<!DOCTYPE html>
<html>
	<head>
	<meta charset="UTF-8">
			
		<link href="https://netdna.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css" rel="stylesheet">
		<link href="https://netdna.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap-theme.min.css" rel="stylesheet">
		<link rel="stylesheet" href="twitter.css" type="text/css" media="screen" />    

	</head>

	<body>

		<?php if(!isset($_SESSION['user_id'])){ ?>
		<div style="float:right;" class="btn-group"><a class="btn btn-lg btn-default" href="register.php">Inscription</a><a class="btn btn-lg btn-default" href="login.php">Connexion</a></div>
		<?php } else { ?>
		
		<a style="float:right;" class="btn btn-lg btn-default" href="logout.php"><i class="glyphicon glyphicon-off"></i></a>
		<?php } ?>
	
		<?php include($template); ?>

	</body>
</html>