<table class="generic-table">
    <?php if(empty($basketItems) == true): ?>
        <tbody>
            <tr>
                <td class="basket-empty">Votre panier est vide pour le moment !</td>
            </tr>
        </tbody>
    <?php else: ?>
        <thead>
            <tr>
                <th class="number">Quantité</th>
                <th>Produit</th>
                <th class="number">Prix Unitaire</th>
                <th class="number">Prix Total</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            <?php foreach($basketItems as $basketItem): ?>
                <tr>
                    <td class="number"><?= $basketItem['quantity'] ?></td>
                    <td><strong><?= $basketItem['name'] ?></strong></td>
                    <td class="number"><?= number_format($basketItem['salePrice'], 2) ?> €</td>
                    <td class="number"><?= number_format($basketItem['salePrice'] * $basketItem['quantity'], 2) ?> €</td>
                    <td>
                        <button class="button button-cancel small" title="Supprimer l'article" data-meal-id="<?= $basketItem['mealId'] ?>">
                            <i class="fa fa-trash"></i>
                        </button>
                    </td>
                </tr>
            <?php endforeach; ?>
        </tbody>
    <?php endif; ?>
</table>