<!DOCTYPE html>
<html>
	<head>
	<meta charset="UTF-8">
			
		<link href="https://netdna.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css" rel="stylesheet">
		<link href="https://netdna.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap-theme.min.css" rel="stylesheet">
		<link rel="stylesheet" href="twitter.css" type="text/css" media="screen" />  

	</head>
	<body>

		<h1>Login</h1>
		<!-- afficher cette div UNIQUEMENT si les identifiants de connexion rentrés sont erronés -->
		<div class="alert alert-danger">

		Mot de passe ou pseudo incorrect.

		</div>

		<form method="post">

			<input type="username" class="form-control" placeholder="Nom d'utilisateur">

			<input type="text" name="password" class="form-control" placeholder="Mot de passe">

		    <input type="submit" class="btn btn-default" value="Connexion">
		
		</form>


	</body>
	
</html>