<h1>TWITTER + !</h1>
<div class="jumbotron">

	<form action="create-post.php" id="twitterForm" method="post">
		<textarea id="tweet"  class="form-control" name="content"></textarea>

		<p><input type="submit" class="btn btn-primary btn-lg" value="Tweet" role="button"></p>
	</form>

</div>

<div id="thread">

	<!-- Afficher tous les posts de la tables "posts" ainsi que leur auteurs respectifs (tables users):  -->
	
	<div class="tweet">
		<span class="author">{{ username }}</span> le {{ created_at }}:
		<p>{{ content }}</p>
		<a href="delete-post.php?post_id={{ id }}" class="delete btn btn-danger btn-xs">Supprimer X</a><a href="update-post.php?post_id={{ id }}" class="delete btn btn-info btn-xs">Editer</a>
	</div>

</div>