<h1>Inscription</h1>
<!-- afficher cette div UNIQUEMENT s'il y a des eu des erreurs lors de l'envoi du formulaire d'inscription -->
<div class="alert alert-danger">

Liste des erreurs éventuelles lors de l'inscription.<br>
<!-- Lister le contenu du tableau contenu dans la variable $errors -->
Exemple (à supprimer):<br>
- Votre pseudo doit faire plus de 5 caractères
- Votre pseudo ne doit contenir que des caractères alphanumérics
</div>

<form method="post">

	<input type="username" class="form-control" placeholder="Nom d'utilisateur">

	<input type="text" name="email" class="form-control" placeholder="Email">

	<input type="text" name="password" class="form-control" placeholder="Mot de passe">

	<input type="submit" class="btn btn-default" value="Envoyer">
		
</form>