<h1>Login</h1>
<!-- afficher cette div UNIQUEMENT si les identifiants de connexion rentrés sont erronés -->
<div class="alert alert-danger">

	Mot de passe ou pseudo incorrect.

</div>

<form method="post">

	<input type="username" class="form-control" placeholder="Nom d'utilisateur">

	<input type="text" name="password" class="form-control" placeholder="Mot de passe">

	<input type="submit" class="btn btn-default" value="Connexion">
		
</form>