	
		<h1>TWITTER + !</h1>
		<div class="jumbotron">

			<?php if(isset($_SESSION['user_id'])){ ?>
			<form action="create-post.php" id="twitterForm" method="post">
			  <textarea id="tweet"  class="form-control" name="content"></textarea>

			  <p><input type="submit" class="btn btn-primary btn-lg" value="Tweet" role="button"></p>
			</form>
			<?php } else { ?>
			
			<div class="alert alert-info">Vous devez être connecté pour poster.</div>
			
			<?php } ?>
		</div>

		<div id="thread">

			<!-- Afficher tous les posts de la tables "posts" ainsi que leur auteurs respectifs (tables users):  -->
			<?php foreach($posts as $post): ?>
			<div class="tweet">
				<span class="author"><?= $post['username'] ?></span> le <?= $post['created_at'] ?>:
				<p><?= htmlentities($post['content']) ?></p>
				<?php if(isset($_SESSION['user_id']) && $_SESSION['user_id']  == $post['user_id']):?>
				<a href="delete-post.php?post_id=<?= $post['id'] ?>&token=<?php echo isset($_SESSION['csrf_token'])?$_SESSION['csrf_token']:''; ?>" class="delete btn btn-danger btn-xs">Supprimer X</a>
				<a href="update-post.php?post_id=<?= $post['id'] ?>" class="delete btn btn-info btn-xs">Editer</a>
				<?php endif ?>
			</div>
			<?php endforeach ?>
		</div>