<h1>Inscription</h1>
<!-- afficher cette div UNIQUEMENT s'il y a des eu des erreurs lors de l'envoi du formulaire d'inscription -->
<?php if(!empty($errors)): ?>
<div class="alert alert-danger">

<!-- Lister le contenu du tableau contenu dans la variable $errors -->

<?php foreach($errors as $error){ ?>

-  <?= $error ?><br>

<?php } 

// Autre possibilité plus rapide:

//echo '- '.implode($errors,'<br>-');

?>
</div>
<?php endif ?>
<form method="post">

	<input type="username" name="username" class="form-control" placeholder="Nom d'utilisateur" value="<?php echo isset($username) ? $username : '';  // Si la variable $username est définie alors on l'affiche ?>">

	<input type="text" name="email" class="form-control" value="<?php echo isset($email) ? $email : '';  // Si la variable $email est définie alors on l'affiche ?>" placeholder="Email">

	<input type="password" name="password" class="form-control" placeholder="Mot de passe">

	<input type="submit" class="btn btn-default" value="Envoyer">
		
</form>