<!DOCTYPE html>
<html>
	<head>
	<meta charset="UTF-8">
			
		<link href="https://netdna.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css" rel="stylesheet">
		<link href="https://netdna.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap-theme.min.css" rel="stylesheet">
		<link rel="stylesheet" href="twitter.css" type="text/css" media="screen" />  

	</head>
	<body>

		<h1>Editer</h1>


		<form method="post">

            <textarea class="form-control" name="content">{{ content }}</textarea>

		    <input type="submit" class="btn btn-default" value="Editer">
		
		</form>


	</body>
	
</html>